//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoeSmoother.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PoeSmoother.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 导出 CSV 的本地化字符串。
        /// </summary>
        public static string DatViewer_Button_ExportCSV {
            get {
                return ResourceManager.GetString("DatViewer_Button_ExportCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string DatViewer_Button_Save {
            get {
                return ResourceManager.GetString("DatViewer_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存为 CSV 文件失败: {0} 的本地化字符串。
        /// </summary>
        public static string DatViewer_ExportCSV_Failed {
            get {
                return ResourceManager.GetString("DatViewer_ExportCSV_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 CSV 文件到 {0} 的本地化字符串。
        /// </summary>
        public static string DatViewer_ExportCSV_Successful {
            get {
                return ResourceManager.GetString("DatViewer_ExportCSV_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存为 CSV 成功 的本地化字符串。
        /// </summary>
        public static string DatViewer_ExportCSV_Successful_Caption {
            get {
                return ResourceManager.GetString("DatViewer_ExportCSV_Successful_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取 dat 失败: {0} 的本地化字符串。
        /// </summary>
        public static string DatWrapper_ParseDatFile_Failed {
            get {
                return ResourceManager.GetString("DatWrapper_ParseDatFile_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有文件处理程序 {0} 的本地化字符串。
        /// </summary>
        public static string DatWrapper_ParseDatFile_Unsupported_File {
            get {
                return ResourceManager.GetString("DatWrapper_ParseDatFile_Unsupported_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存失败: {0} 的本地化字符串。
        /// </summary>
        public static string DatWrapper_Save_Failed {
            get {
                return ResourceManager.GetString("DatWrapper_Save_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已保存 &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        public static string DatWrapper_Save_Successful {
            get {
                return ResourceManager.GetString("DatWrapper_Save_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已保存 的本地化字符串。
        /// </summary>
        public static string DatWrapper_Save_Successful_Caption {
            get {
                return ResourceManager.GetString("DatWrapper_Save_Successful_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        public static string Error_Caption {
            get {
                return ResourceManager.GetString("Error_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取目录树失败: {0} 的本地化字符串。
        /// </summary>
        public static string Error_Read_Directory_Tree {
            get {
                return ResourceManager.GetString("Error_Read_Directory_Tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 selectedRecord.Name 的本地化字符串。
        /// </summary>
        public static string ExportAllItemsInDirectory_Default_FileName {
            get {
                return ResourceManager.GetString("ExportAllItemsInDirectory_Default_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出文件失败: {0} 的本地化字符串。
        /// </summary>
        public static string ExportAllItemsInDirectory_Failed {
            get {
                return ResourceManager.GetString("ExportAllItemsInDirectory_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 {0} 文件 的本地化字符串。
        /// </summary>
        public static string ExportAllItemsInDirectory_Successful {
            get {
                return ResourceManager.GetString("ExportAllItemsInDirectory_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出成功 的本地化字符串。
        /// </summary>
        public static string ExportAllItemsInDirectory_Successful_Caption {
            get {
                return ResourceManager.GetString("ExportAllItemsInDirectory_Successful_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出文件失败: {0} 的本地化字符串。
        /// </summary>
        public static string ExportSelectedItem_Failed {
            get {
                return ResourceManager.GetString("ExportSelectedItem_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 {0} 字节 的本地化字符串。
        /// </summary>
        public static string ExportSelectedItem_Successful {
            get {
                return ResourceManager.GetString("ExportSelectedItem_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件偏移量: 的本地化字符串。
        /// </summary>
        public static string LabelFileOFfset_Content {
            get {
                return ResourceManager.GetString("LabelFileOFfset_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GGPK Pack File|*.ggpk 的本地化字符串。
        /// </summary>
        public static string Load_GGPK_Filter {
            get {
                return ResourceManager.GetString("Load_GGPK_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只能拉取单独一个文件、文件夹或zip压缩包 的本地化字符串。
        /// </summary>
        public static string MainWindow_Drop_Failed {
            get {
                return ResourceManager.GetString("MainWindow_Drop_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用内容到 {0} 的本地化字符串。
        /// </summary>
        public static string MainWindow_HandleDropArchive_Info {
            get {
                return ResourceManager.GetString("MainWindow_HandleDropArchive_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件数量 = {0} 的本地化字符串。
        /// </summary>
        public static string MainWindow_HandleDropDirectory_Count {
            get {
                return ResourceManager.GetString("MainWindow_HandleDropDirectory_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能替换文件  {0} -&gt; 找不到 的本地化字符串。
        /// </summary>
        public static string MainWindow_HandleDropDirectory_Failed {
            get {
                return ResourceManager.GetString("MainWindow_HandleDropDirectory_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 替换中 {0} 的本地化字符串。
        /// </summary>
        public static string MainWindow_HandleDropDirectory_Replace {
            get {
                return ResourceManager.GetString("MainWindow_HandleDropDirectory_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须在左边的目录树中选择一个要替换的目标文件 的本地化字符串。
        /// </summary>
        public static string MainWindow_HandleDropFile_Failed {
            get {
                return ResourceManager.GetString("MainWindow_HandleDropFile_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 替换中 {0}{1} 的本地化字符串。
        /// </summary>
        public static string MainWindow_HandleDropFile_Replace {
            get {
                return ResourceManager.GetString("MainWindow_HandleDropFile_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hash: 的本地化字符串。
        /// </summary>
        public static string MainWindow_Label_FileHash {
            get {
                return ResourceManager.GetString("MainWindow_Label_FileHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名字 Hash: 的本地化字符串。
        /// </summary>
        public static string MainWindow_Label_FileNameHash {
            get {
                return ResourceManager.GetString("MainWindow_Label_FileNameHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件偏移量: 的本地化字符串。
        /// </summary>
        public static string MainWindow_Label_FileOffset {
            get {
                return ResourceManager.GetString("MainWindow_Label_FileOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件大小: 的本地化字符串。
        /// </summary>
        public static string MainWindow_Label_FileSize {
            get {
                return ResourceManager.GetString("MainWindow_Label_FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        public static string MainWindow_Menu_Export {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 替换 的本地化字符串。
        /// </summary>
        public static string MainWindow_Menu_Replace {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看 的本地化字符串。
        /// </summary>
        public static string MainWindow_Menu_View {
            get {
                return ResourceManager.GetString("MainWindow_Menu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VisualGGPK (只读模式) 的本地化字符串。
        /// </summary>
        public static string MainWindow_Title_Readonly {
            get {
                return ResourceManager.GetString("MainWindow_Title_Readonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本检查失败. 的本地化字符串。
        /// </summary>
        public static string MainWindow_VersionCheck_Failed {
            get {
                return ResourceManager.GetString("MainWindow_VersionCheck_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否替换文件? 的本地化字符串。
        /// </summary>
        public static string MainWindow_Window_Drop_Confirm {
            get {
                return ResourceManager.GetString("MainWindow_Window_Drop_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认替换 的本地化字符串。
        /// </summary>
        public static string MainWindow_Window_Drop_Confirm_Caption {
            get {
                return ResourceManager.GetString("MainWindow_Window_Drop_Confirm_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取文件失败: {0} 的本地化字符串。
        /// </summary>
        public static string ReloadGGPK_Failed {
            get {
                return ResourceManager.GetString("ReloadGGPK_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ***只读模式打开 GGPK（一般是游戏没有退出造成） *** 的本地化字符串。
        /// </summary>
        public static string ReloadGGPK_ReadOnly {
            get {
                return ResourceManager.GetString("ReloadGGPK_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部完成! 的本地化字符串。
        /// </summary>
        public static string ReloadGGPK_Successful {
            get {
                return ResourceManager.GetString("ReloadGGPK_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 遍历目录树.... 的本地化字符串。
        /// </summary>
        public static string ReloadGGPK_Traversing_Tree {
            get {
                return ResourceManager.GetString("ReloadGGPK_Traversing_Tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 替换文件失败: {0} 的本地化字符串。
        /// </summary>
        public static string ReplaceItem_Failed {
            get {
                return ResourceManager.GetString("ReplaceItem_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GGPK处于只读模式 的本地化字符串。
        /// </summary>
        public static string ReplaceItem_Readonly {
            get {
                return ResourceManager.GetString("ReplaceItem_Readonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不能写入GGPK 的本地化字符串。
        /// </summary>
        public static string ReplaceItem_Readonly_Caption {
            get {
                return ResourceManager.GetString("ReplaceItem_Readonly_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记录 {0} 已更新并更新到偏移量 {1} 的本地化字符串。
        /// </summary>
        public static string ReplaceItem_Successful {
            get {
                return ResourceManager.GetString("ReplaceItem_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 替换成功 的本地化字符串。
        /// </summary>
        public static string ReplaceItem_Successful_Caption {
            get {
                return ResourceManager.GetString("ReplaceItem_Successful_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  * 无法预览，如需查看请导出后使用正确的软件打开 *
        ///
        ///详情: {0} 的本地化字符串。
        /// </summary>
        public static string UpdateDisplayPanel_Failed {
            get {
                return ResourceManager.GetString("UpdateDisplayPanel_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未能提取查看的文件: {0} 的本地化字符串。
        /// </summary>
        public static string ViewSelectedItem_Failed {
            get {
                return ResourceManager.GetString("ViewSelectedItem_Failed", resourceCulture);
            }
        }
    }
}
