//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoeSmoother.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_enUS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_enUS() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PoeSmoother.Properties.Resources.enUS", typeof(Resources_enUS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 - Remember to back up your Client.ggpk before starting to change anything. 的本地化字符串。
        /// </summary>
        public static string About_Msg_1 {
            get {
                return ResourceManager.GetString("About_Msg_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 - To reset things to default, just check / uncheck the options twice. 的本地化字符串。
        /// </summary>
        public static string About_Msg_2 {
            get {
                return ResourceManager.GetString("About_Msg_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 - Skills have 3 options: improved(lagless),zero effects(invisible effects) and default values(original game effects). Check them twice if you change your mind, from zero to improved or just to leave them by default. 的本地化字符串。
        /// </summary>
        public static string About_Msg_3 {
            get {
                return ResourceManager.GetString("About_Msg_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 - Paths used by customs options:
        ///&gt; particles: Metadata/...
        ///&gt; sounds: Metadata/...
        ///&gt; skills: Metadata/...
        ///&gt; ui changes: Art/... 的本地化字符串。
        /// </summary>
        public static string About_Msg_4 {
            get {
                return ResourceManager.GetString("About_Msg_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 zero effects equals to: no sounds and effects for monsters/skills. 的本地化字符串。
        /// </summary>
        public static string About_Msg_5 {
            get {
                return ResourceManager.GetString("About_Msg_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 *Compile/MOD:光影路西法. based on PoeSmoother. 的本地化字符串。
        /// </summary>
        public static string About_Msg_6 {
            get {
                return ResourceManager.GetString("About_Msg_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;Github-SourceCode&gt; 的本地化字符串。
        /// </summary>
        public static string About_Msg_7 {
            get {
                return ResourceManager.GetString("About_Msg_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View in browser 的本地化字符串。
        /// </summary>
        public static string About_Msg_7_2 {
            get {
                return ResourceManager.GetString("About_Msg_7_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;My Blog&gt; 的本地化字符串。
        /// </summary>
        public static string About_Msg_8 {
            get {
                return ResourceManager.GetString("About_Msg_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View in browser 的本地化字符串。
        /// </summary>
        public static string About_Msg_8_2 {
            get {
                return ResourceManager.GetString("About_Msg_8_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;Complete!&gt; 的本地化字符串。
        /// </summary>
        public static string All_Done {
            get {
                return ResourceManager.GetString("All_Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export CSV 的本地化字符串。
        /// </summary>
        public static string DatViewer_Button_ExportCSV {
            get {
                return ResourceManager.GetString("DatViewer_Button_ExportCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        public static string DatViewer_Button_Save {
            get {
                return ResourceManager.GetString("DatViewer_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to save CSV file: {0} 的本地化字符串。
        /// </summary>
        public static string DatViewer_ExportCSV_Failed {
            get {
                return ResourceManager.GetString("DatViewer_ExportCSV_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saved CSV file to {0} 的本地化字符串。
        /// </summary>
        public static string DatViewer_ExportCSV_Successful {
            get {
                return ResourceManager.GetString("DatViewer_ExportCSV_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successfully saved CSV 的本地化字符串。
        /// </summary>
        public static string DatViewer_ExportCSV_Successful_Caption {
            get {
                return ResourceManager.GetString("DatViewer_ExportCSV_Successful_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to read dat: {0} 的本地化字符串。
        /// </summary>
        public static string DatWrapper_ParseDatFile_Failed {
            get {
                return ResourceManager.GetString("DatWrapper_ParseDatFile_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No handler for file {0} 的本地化字符串。
        /// </summary>
        public static string DatWrapper_ParseDatFile_Unsupported_File {
            get {
                return ResourceManager.GetString("DatWrapper_ParseDatFile_Unsupported_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to save: {0} 的本地化字符串。
        /// </summary>
        public static string DatWrapper_Save_Failed {
            get {
                return ResourceManager.GetString("DatWrapper_Save_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saved &apos;{0}&apos; 的本地化字符串。
        /// </summary>
        public static string DatWrapper_Save_Successful {
            get {
                return ResourceManager.GetString("DatWrapper_Save_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Saved 的本地化字符串。
        /// </summary>
        public static string DatWrapper_Save_Successful_Caption {
            get {
                return ResourceManager.GetString("DatWrapper_Save_Successful_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        public static string Error_Caption {
            get {
                return ResourceManager.GetString("Error_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to read directory tree: {0} 的本地化字符串。
        /// </summary>
        public static string Error_Read_Directory_Tree {
            get {
                return ResourceManager.GetString("Error_Read_Directory_Tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 selectedRecord.Name 的本地化字符串。
        /// </summary>
        public static string ExportAllItemsInDirectory_Default_FileName {
            get {
                return ResourceManager.GetString("ExportAllItemsInDirectory_Default_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to export item(s): {0} 的本地化字符串。
        /// </summary>
        public static string ExportAllItemsInDirectory_Failed {
            get {
                return ResourceManager.GetString("ExportAllItemsInDirectory_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exported {0} files 的本地化字符串。
        /// </summary>
        public static string ExportAllItemsInDirectory_Successful {
            get {
                return ResourceManager.GetString("ExportAllItemsInDirectory_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export successful 的本地化字符串。
        /// </summary>
        public static string ExportAllItemsInDirectory_Successful_Caption {
            get {
                return ResourceManager.GetString("ExportAllItemsInDirectory_Successful_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to export item: {0} 的本地化字符串。
        /// </summary>
        public static string ExportSelectedItem_Failed {
            get {
                return ResourceManager.GetString("ExportSelectedItem_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exported {0} bytes 的本地化字符串。
        /// </summary>
        public static string ExportSelectedItem_Successful {
            get {
                return ResourceManager.GetString("ExportSelectedItem_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JSON Parse Failed: 的本地化字符串。
        /// </summary>
        public static string JSON_Parse_Failed {
            get {
                return ResourceManager.GetString("JSON_Parse_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Offset: 的本地化字符串。
        /// </summary>
        public static string LabelFileOFfset_Content {
            get {
                return ResourceManager.GetString("LabelFileOFfset_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GGPK Pack File|*.ggpk 的本地化字符串。
        /// </summary>
        public static string Load_GGPK_Filter {
            get {
                return ResourceManager.GetString("Load_GGPK_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_Exit {
            get {
                return ResourceManager.GetString("MainWindow_Button_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换为中文 的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_Location_CN {
            get {
                return ResourceManager.GetString("MainWindow_Button_Location_CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Switch to English 的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_Location_US {
            get {
                return ResourceManager.GetString("MainWindow_Button_Location_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minimize 的本地化字符串。
        /// </summary>
        public static string MainWindow_Button_Min {
            get {
                return ResourceManager.GetString("MainWindow_Button_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can only drop a single file, directory, or zip file 的本地化字符串。
        /// </summary>
        public static string MainWindow_Drop_Failed {
            get {
                return ResourceManager.GetString("MainWindow_Drop_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Nofound: 的本地化字符串。
        /// </summary>
        public static string MainWindow_Error_File_Nofound {
            get {
                return ResourceManager.GetString("MainWindow_Error_File_Nofound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 At   的本地化字符串。
        /// </summary>
        public static string MainWindow_Error_In {
            get {
                return ResourceManager.GetString("MainWindow_Error_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Applying contents of {0} 的本地化字符串。
        /// </summary>
        public static string MainWindow_HandleDropArchive_Info {
            get {
                return ResourceManager.GetString("MainWindow_HandleDropArchive_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File count = {0} 的本地化字符串。
        /// </summary>
        public static string MainWindow_HandleDropDirectory_Count {
            get {
                return ResourceManager.GetString("MainWindow_HandleDropDirectory_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to replace file {0} -&gt; Missing 的本地化字符串。
        /// </summary>
        public static string MainWindow_HandleDropDirectory_Failed {
            get {
                return ResourceManager.GetString("MainWindow_HandleDropDirectory_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replacing {0} 的本地化字符串。
        /// </summary>
        public static string MainWindow_HandleDropDirectory_Replace {
            get {
                return ResourceManager.GetString("MainWindow_HandleDropDirectory_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Must select a file to replace in the tree view 的本地化字符串。
        /// </summary>
        public static string MainWindow_HandleDropFile_Failed {
            get {
                return ResourceManager.GetString("MainWindow_HandleDropFile_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replacing {0}{1} 的本地化字符串。
        /// </summary>
        public static string MainWindow_HandleDropFile_Replace {
            get {
                return ResourceManager.GetString("MainWindow_HandleDropFile_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hash: 的本地化字符串。
        /// </summary>
        public static string MainWindow_Label_FileHash {
            get {
                return ResourceManager.GetString("MainWindow_Label_FileHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name Hash: 的本地化字符串。
        /// </summary>
        public static string MainWindow_Label_FileNameHash {
            get {
                return ResourceManager.GetString("MainWindow_Label_FileNameHash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Offset: 的本地化字符串。
        /// </summary>
        public static string MainWindow_Label_FileOffset {
            get {
                return ResourceManager.GetString("MainWindow_Label_FileOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File Size: 的本地化字符串。
        /// </summary>
        public static string MainWindow_Label_FileSize {
            get {
                return ResourceManager.GetString("MainWindow_Label_FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 *** Successful! Please restart the program ***
        ///***切换成功，请重新打开程序生效*** 的本地化字符串。
        /// </summary>
        public static string MainWindow_Location_Msg {
            get {
                return ResourceManager.GetString("MainWindow_Location_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export 的本地化字符串。
        /// </summary>
        public static string MainWindow_Menu_Export {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recovery 的本地化字符串。
        /// </summary>
        public static string MainWindow_Menu_Recovery {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recovery Success! 的本地化字符串。
        /// </summary>
        public static string MainWindow_Menu_Recovery_Success {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Recovery_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replace 的本地化字符串。
        /// </summary>
        public static string MainWindow_Menu_Replace {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  Replace Success 的本地化字符串。
        /// </summary>
        public static string MainWindow_Menu_Replace_Success {
            get {
                return ResourceManager.GetString("MainWindow_Menu_Replace_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View 的本地化字符串。
        /// </summary>
        public static string MainWindow_Menu_View {
            get {
                return ResourceManager.GetString("MainWindow_Menu_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VisualGGPK (Read-Only) 的本地化字符串。
        /// </summary>
        public static string MainWindow_Title_Readonly {
            get {
                return ResourceManager.GetString("MainWindow_Title_Readonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version check failed. 的本地化字符串。
        /// </summary>
        public static string MainWindow_VersionCheck_Failed {
            get {
                return ResourceManager.GetString("MainWindow_VersionCheck_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replace files? 的本地化字符串。
        /// </summary>
        public static string MainWindow_Window_Drop_Confirm {
            get {
                return ResourceManager.GetString("MainWindow_Window_Drop_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm replace 的本地化字符串。
        /// </summary>
        public static string MainWindow_Window_Drop_Confirm_Caption {
            get {
                return ResourceManager.GetString("MainWindow_Window_Drop_Confirm_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Effects 的本地化字符串。
        /// </summary>
        public static string MainWindow_Window_Tab_Effects_Header {
            get {
                return ResourceManager.GetString("MainWindow_Window_Tab_Effects_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About* 的本地化字符串。
        /// </summary>
        public static string MainWindow_Window_Tab_Info_Header {
            get {
                return ResourceManager.GetString("MainWindow_Window_Tab_Info_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Skills 的本地化字符串。
        /// </summary>
        public static string MainWindow_Window_Tab_Skills_Header {
            get {
                return ResourceManager.GetString("MainWindow_Window_Tab_Skills_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to read file: {0} 的本地化字符串。
        /// </summary>
        public static string ReloadGGPK_Failed {
            get {
                return ResourceManager.GetString("ReloadGGPK_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ***Opening GGPK in read-only mode *** 的本地化字符串。
        /// </summary>
        public static string ReloadGGPK_ReadOnly {
            get {
                return ResourceManager.GetString("ReloadGGPK_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 All done! 的本地化字符串。
        /// </summary>
        public static string ReloadGGPK_Successful {
            get {
                return ResourceManager.GetString("ReloadGGPK_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Traversing tree.... 的本地化字符串。
        /// </summary>
        public static string ReloadGGPK_Traversing_Tree {
            get {
                return ResourceManager.GetString("ReloadGGPK_Traversing_Tree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to replace item: {0} 的本地化字符串。
        /// </summary>
        public static string ReplaceItem_Failed {
            get {
                return ResourceManager.GetString("ReplaceItem_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GGPK open in read-only mode 的本地化字符串。
        /// </summary>
        public static string ReplaceItem_Readonly {
            get {
                return ResourceManager.GetString("ReplaceItem_Readonly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot write to GGPK 的本地化字符串。
        /// </summary>
        public static string ReplaceItem_Readonly_Caption {
            get {
                return ResourceManager.GetString("ReplaceItem_Readonly_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Record {0} updated and relocated to offset {1} 的本地化字符串。
        /// </summary>
        public static string ReplaceItem_Successful {
            get {
                return ResourceManager.GetString("ReplaceItem_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Replacement successful 的本地化字符串。
        /// </summary>
        public static string ReplaceItem_Successful_Caption {
            get {
                return ResourceManager.GetString("ReplaceItem_Successful_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 * Unable to view item, export it if you want to view it *
        ///
        ///Details: {0} 的本地化字符串。
        /// </summary>
        public static string UpdateDisplayPanel_Failed {
            get {
                return ResourceManager.GetString("UpdateDisplayPanel_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to extract file for viewing: {0} 的本地化字符串。
        /// </summary>
        public static string ViewSelectedItem_Failed {
            get {
                return ResourceManager.GetString("ViewSelectedItem_Failed", resourceCulture);
            }
        }
    }
}
